### ISSUE TITLE
Empty strings can lead to crash

### ISSUE THREAD

**Issue by hansdthuis** [josephalevin/fson#10]
I bumped into a case in which the parser crashed due to the presence of an empty string
I changed the code slightly and initialized last. Somehow the character last had the value "/".

This is my new code

      function parse_string(unit) result(string)
        integer, intent(inout) :: unit
        type(fson_string), pointer :: string

        logical :: eof
        character :: c, last

        string => fson_string_create()
        last = " "
        do
...
        end do
      end function parse_string

**Comment by acroucher** [comment]
Fixed this as suggested.
