### ISSUE TITLE
Unit tests (too long double precision values are not parsed correctly)

### ISSUE THREAD

**Issue by jmozmoz** [josephalevin/fson#11]
I am not sure that this project is still maintained: If yes, I have added unit tests based on fruit (http://sourceforge.net/apps/mediawiki/fortranxunit/index.php?title=Main_Page) in the branch https://github.com/jmozmoz/fson/tree/fruit_tests
(I also added the feature to parse a string instead of a file)

The first tests show e.g. that too long double precision values (in the sense of too many digits) are parsed incorrectly. 

Also reals in scientific notation are not parsed correctly.

**Comment by acroucher** [comment]
Fixed now, since my fork has been merged in.
