### ISSUE TITLE
callback example.

### ISSUE THREAD

**Issue by rgavazzi** [josephalevin/fson#12]
Hi,
I've just found your project very useful for a f90 code I'm developing and that will interact with a webinterface through JSON file exchanges. I'd like to be able to use fson_get calls, involving JSON arrays.  I am looking forward for having an extract example involving the callback routine.  The example below fails for the  2nd and 3rd  fson_get calls. For the 2nd, I understand it's far from the syntax you've anticipated with the callback placeholder, but for the 3rd case, I get a segfault! 

Did I miss anything?
thanks again for releasing this very nice piece of code!

---

Example file that fails 
<pre>
program example1

    ! Typical usage should only require an explicit use of the fson module.
    ! The other modules will be used privatley by fson as required.  
    use fson

    ! declare a pointer variable.  Always use a pointer with fson_value.
    type(fson_value), pointer :: value, p
    character(len=100) :: fn
    integer :: vv,vvv(2)
    character(len=50) :: fff
    real(4) :: d

     call get_command_argument(1,fn)

    ! parse the json file
    value => fson_parse(fn)

    ! print the parsed data to the console
    call fson_print(value)

    ! extract data from the parsed value        

    print *,"--------------------------"
    call fson_get( this=value, value=vv, path="Correl.ID2" )
    print*,"vv= ",vv

    call fson_get( this=value, value=vvv, path="Correl.ID1" )
    print*,"vvv= ",vvv

    call fson_get( this=value, value=d, path="Prior[3].mode" )
    print*,"d= ",d

    ! clean up
    call fson_destroy(value)

end program example1
</pre>

Associated json input file.

<pre>
{
    "Prior" :
    [    
	{
	    "ID" : [1,3] ,
	    "type" : "cyclic" ,
	    "period" : 180
	},
	{
	    "ID" : [3,4] ,
	    "type" : "uniform",
	    "LowBound" : 0,
	    "HighBound" : 1
	},
	{
	    "ID" : [3,1] ,
	    "type" : "Normal" ,
	    "mode" : 0.3  ,
	    "width" : 40. ,
	    "LowBound" : null ,
	    "HighBound" : null 
	},
	{
	    "ID" : [3,3] ,
	    "type" : "LogNormal",
	    "mode" :  100. ,
	    "width" : 0.2,
	    "LowBound" : null,
	    "HighBound" : null
	},
	{
	    "ID" : [2,2] ,
	    "type" : "ImgPos2", 
	    "x" : 0.4 ,
	    "y" : 0.5 ,
	    "a" : 0.3 ,
	    "b" : 0.2 ,
	    "theta" : 40 
	},
	{
	    "ID" : [1,1] ,
	    "type" : "SrcPos1", 
	    "x" : 0.4,
	    "y" : 0.5,
	    "a" : 0.4
	},
	{
	    "ID" : [1,4] ,
	    "type" : "Ellip2" ,
	    "width" : 0.3 ,
	    "highBound" : 1.0
	}
    ]
    ,
    "Correl" :
    {
	"ID1" : [1,2] ,
	"ID2" : 3 ,
	"correl" : 0.99,
    }
    
}
</pre>

**Comment by acroucher** [comment]
The code above now works with fson, with some minor modifications:

- declare vvv as allocatable: `integer, allocatable :: vvv(:)`
- get value of vvv in two steps: first `call fson_get(value, "Correl", p)`, then `call fson_get(p, "ID1", vvv)`
- getting `Prior[3].mode` seems to work fine now- no modifications needed.
