### ISSUE TITLE
Parse string with escaped character

### ISSUE THREAD

**Issue by maxhaz** [josephalevin/fson#14]
If I am correct, there might be an issue with strings that contain escaped character.
According to JSON spec:

> So, for example, a string containing only a single reverse solidus character may be represented as "\\\".

In the current implementation (and the forked ones), this valid JSON string:

    "\\"

gives an error because the second double quote seems to be escaped (and end of string is missing).
 
Then the string:
 
    "\\ "
doesn't produce an error but the resulting string is incorrect, as the backslash is not escaped.

**Comment by acroucher** [comment]
Just added this fix.
