### ISSUE TITLE
JSON array with no label

### ISSUE THREAD

**Issue by doom99** [josephalevin/fson#21]
so I have data coming to me from an external site that appears similar to the below.  Is there a way to reference this array with FSON? 

[ {
  "a" : "string",
  "b" : "string"
}
, {
  "a" : "string",
  "b" : "string"
}
]

I can hack the file if absolutely necessary to add this around everything but would prefer not to if possible

{ "label":
....
}

**Comment by acroucher** [comment]
Yes, you can parse this, e.g.:

```fortran
type(fson_value), pointer :: data
integer :: count, i
type(fson_value), pointer :: dict, item
character(len = 8) :: str

data => fson_parse("nolabel.json")
count = fson_value_count(data)
do i = 1, count
  dict => fson_value_get(data, i)
  item => fson_value_get(dict, "a")
  call fson_get(item, "", str)
  ! do something with str
end do
call fson_destroy(data)

```
This will give you access to the string values in each dictionary.
