### ISSUE TITLE
ERROR: Unexpected character while parsing value. 'E' ASCII=          69

### ISSUE THREAD

**Issue by geresie** [josephalevin/fson#23]
Hi, 
I reinstalled and compiled fson-master on a different machine and I got the following error message after running my code:
ERROR: Unexpected character while parsing value. 'E' ASCII=          69. 
I was able to run my code and parse JSON files with no errors before.
What can cause this error?
Many Thanks

**Comment by acroucher** [comment]
It looks like this error is generated in the subroutine parse_value(), where it tries to parse the first character of a data value and decide what type it is (object, array, string, logical, null or number). In your case it is encountering the character 'E' which it doesn't know what to do with. For example, could it be a string value that you have forgotten to put quotes around?

Are you able to post a short piece of JSON that causes the error? First you could try validating  your file using e.g. https://jsonlint.com/ (if you haven't already).

**Comment by geresie** [comment]
Dear Adrian,
thank you so much for your answer and help.
I was able to find the problem and corrected it. Now everything runs
smoothly.
I checked all of my JSON files with the tool you mentioned.
For some reason, I have not checked all of them before and the ones that
had the error I did not even think of checking before.
Thanks SO much,
Erika
