### ISSUE TITLE
Error parsing real numbers with negative exponents

### ISSUE THREAD

**Issue by apthorpe** [josephalevin/fson#8]
There appears to be an error in parsing real numbers with negative exponents (e.g. 4.14112E-1). I have a test case which parses 4.14112E1 correctly but dies if the exponent is changed from 1 to -1.

A test file which can invoke this issue is posted at https://gist.github.com/apthorpe/d27f2eddbffd3a747b0d

**Comment by acroucher** [comment]
Fixed now, since my fork has been merged in.
