### ISSUE TITLE
Spaces are stripped from string values

### ISSUE THREAD

**Issue by apthorpe** [josephalevin/fson#9]
Running the example code against a JSON sample showed spaces being stripped from string values.

A test file which can invoke this issue (same as link in previous issue) is posted at https://gist.github.com/apthorpe/d27f2eddbffd3a747b0d

Also, it seems that carriage returns may be prepended to parsed strings, though that may just be a printing artifact and not a parser issue; I haven't looked into it in depth yet and didn't want to open a separate issue for it until I do.

**Comment by acroucher** [comment]
Fixed now, since my fork has been merged in.
